
services:
  app:
    image: mlservice:latest
    env_file:
      - ./app/.env
    build: 
      context: ./app/
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
  web-proxy:
    image: nginx:latest
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  database:
    image: postgres:latest
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8-management
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq




